### PR TITLE
Add some optimizations

### PR DESCRIPTION
**Pull request by gdyuldin**
* Replace `np.e ** <smth>` with `np.exp(<smth>)`.
* Replace `set(np.ndarray)` with `np.unique(np.ndarray)`.
* Update computing `matrix_wires_unconnected`.

Firs 2 changes are faster, because it uses numpy optimization and skips converting numpy objects to pure python (np.int64 -> int). Last change check connectivity between ech pair of wires, instead of each pair of pulse and significant reduces computation time.

### CODE REVIEW

**Comment by gdyuldin** [comment]
Execution times on my machine ( for `pymininec -T $(grep -v '#' test/12-el.pym ) > /dev/null`):
Old:
```
Time   0.587 for compute_impedance_matrix
Time   0.000 for compute_rhs
Time   0.002 for compute_currents
Time   0.133 for compute_far_field
```

New:
```
Time   0.363 for compute_impedance_matrix
Time   0.000 for compute_rhs
Time   0.002 for compute_currents
Time   0.115 for compute_far_field

```

**Comment by schlatterbeck** [comment]
Hi gdyuldin, thanks for the patch, performance improvement is amazing.

Some minor nitpicks:

- Why did you introduce 'wires_connected' in pulse.py (and changed the semantics when it was *and* before and is now *or* -- not that this matters but you could have removed the second call alltogether), I'd rather keep the call to w1.is_connected. Since the connection is symmetrical you need only one call.
- also in pulse.py: wires already have a number, wire.n, this saves two enumerates in the new matrix_wires_unconnected
- also in pulse.py: repeatedly searching in the wires list is O(n^2) in the number of wires, better use a dict indexed with wire.n
- Can you adhere to my coding style of placing a space before an opening parenthesis or angular bracket?
- The introduction of np.allclose in the test changes semantics because it uses a different precision.

I first feared that removing the trailing spaces would break doctests but apparently doctest has improved in that regard.

Some of that code looks machine generated, what tools are you using?

Thanks
Ralf

**Comment by gdyuldin** [comment]
> Why did you introduce 'wires_connected' in pulse.py (and changed the semantics when it was and before and is now or -- not that this matters but you could have removed the second call alltogether), I'd rather keep the call to w1.is_connected. Since the connection is symmetrical you need only one call.

My first idea was to use `functools.lru_cache` for this function to reduce actual calls. I just forgot to revert it. 

> also in pulse.py: wires already have a number, wire.n, this saves two enumerates in the new matrix_wires_unconnected
also in pulse.py: repeatedly searching in the wires list is O(n^2) in the number of wires, better use a dict indexed with wire.n

I was not sure, that each wire has `n`. `Wire::__str__` method has a variant for absent `n`. Agree, using `n` will be faster.

> Can you adhere to my coding style of placing a space before an opening parenthesis or angular bracket?

It's not a pythonic code style, but OK

> The introduction of np.allclose in the test changes semantics because it uses a different precision.

It has `atol` parameter. I guess using `np.allclose` is clearer, but I can revert this change.

> I first feared that removing the trailing spaces would break doctests but apparently doctest has improved in that regard.

It's my VSCode default configuration - remove all trailing spaces on save. 

> Some of that code looks machine generated, what tools are you using?
All code was written by me)

And - great job of porting mininec to python. thanks!

**Comment by schlatterbeck** [comment]
On Wed, Apr 10, 2024 at 12:21:33AM -0700, Georgy Dyuldin wrote:
> > Why did you introduce 'wires_connected' in pulse.py (and changed the
> > semantics when it was and before and is now or -- not that this
> > matters but you could have removed the second call alltogether), I'd
> > rather keep the call to w1.is_connected. Since the connection is
> > symmetrical you need only one call.
> 
> My first idea was to use `functools.lru_cache` for this function to
> reduce actual calls. I just forgot to revert it. 

Thanks, looks good!

> > also in pulse.py: wires already have a number, wire.n, this saves two enumerates in the new matrix_wires_unconnected
> also in pulse.py: repeatedly searching in the wires list is O(n^2) in the number of wires, better use a dict indexed with wire.n
> 
> I was not sure, that each wire has `n`. `Wire::__str__` method has a
> variant for absent `n`. Agree, using `n` will be faster.

Thanks!
The 'n' is assigned when segments and pulses are computed. So at the
point where we use pulses we're guaranteed to have n set.

> > Can you adhere to my coding style of placing a space before an
> > opening parenthesis or angular bracket?
> 
> It's not a pythonic code style, but OK

I know :-)

> > The introduction of np.allclose in the test changes semantics
> > because it uses a different precision.
> 
> It has `atol` parameter. I guess using `np.allclose` is clearer, but I
> can revert this change.

Thanks, looks good!

> It's my VSCode default configuration - remove all trailing spaces on save. 

Yes, maybe I should do something similar. I was not aware that I had so
much trailing space.

> > Some of that code looks machine generated, what tools are you using?
> All code was written by me)

OK sorry for that :-)
I was hoping there would be a tools that looks for common improvements
in numpy code. The fact that it was inserted without looking at the
coding style surrounding it ...

> And - great job of porting mininec to python. thanks!

Thanks for the contribution, I'm about to merge it.

Ralf
-- 
Dr. Ralf Schlatterbeck                  Tel:   +43/2243/26465-16
Open Source Consulting                  www:   www.runtux.com
Reichergasse 131, A-3411 Weidling       email: ***@***.***

**Pull request merged**
